square_length = float(input("Enter the length of side of the square : "))
rect_length = float(input("Enter the length of the rectangle : "))
rect_breadth = float(input("Enter the breadth of the rectangle : "))
print("The perimeter of square is ", 4*square_length)
print("The area of square is ", square_length**2)
print("--------------------------------------------------------")
print("The perimeter of rectangle is ", 2*(rect_length+rect_breadth))
print("The area of rectangle is ", rect_breadth*rect_length)